export const CREATE_PDF_CATEGARY = "CREATE_PDF_CATEGARY";
export const CREATE_PDF_CATEGARY_SUCCESS = "CREATE_PDF_CATEGARY_SUCCESS";
export const CREATE_PDF_CATEGARY_FAILED = "CREATE_PDF_CATEGARY_FAILED";
export const FETCH_ALL_PDF_CATEGARIES = "FETCH_ALL_PDF_CATEGARIES";
export const FETCH_ALL_PDF_CATEGARIES_SUCCESS = "FETCH_ALL_PDF_CATEGARIES_SUCCESS";
export const FETCH_ALL_PDF_CATEGARIES_FAILED = "FETCH_ALL_PDF_CATEGARIES_FAILED"